"""
Slack API wrapper for sending alerts and receiving slash commands.
Uses Incoming Webhooks for zero-cost integration.
"""
import httpx
from backend.app.config import get_settings

settings = get_settings()


def send_alert(incident_data: dict) -> dict:
    """
    Sends a formatted alert to the Slack channel via webhook.
    """
    if not settings.SLACK_WEBHOOK_URL:
        print("⚠️ SLACK_WEBHOOK_URL not configured. Skipping Slack alert.")
        return {"status": "skipped", "reason": "No webhook URL configured"}
    
    # Extract data
    service = incident_data.get("service", "unknown")
    anomaly = incident_data.get("anomaly_report", {})
    rca = incident_data.get("rca_report", {})
    fix = incident_data.get("fix_suggestion", {})
    
    # Format the message
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "🚨 ROOTMIND INCIDENT ALERT",
                "emoji": True
            }
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Service:*\n{service}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Severity:*\nCRITICAL"
                }
            ]
        }
    ]
    
    # Add anomaly details
    if anomaly and "assessment" in anomaly:
        assessment = anomaly["assessment"]
        features = assessment.get("features", {})
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Anomaly Detected*\n• CPU: {features.get('cpu_usage', 'N/A')}%\n• Memory: {features.get('memory_usage', 'N/A')}%\n• Latency: {features.get('request_latency_ms', 'N/A')}ms\n• Error Rate: {features.get('error_rate', 'N/A')}%"
            }
        })
    
    # Add root cause if available
    if rca and "root_cause" in rca:
        root_cause = rca["root_cause"]
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*🔍 Root Cause*\n{root_cause.get('root_cause_summary', 'N/A')}\n\n*Responsible File:* `{root_cause.get('responsible_file', 'N/A')}`\n*Commit:* `{root_cause.get('suspected_commit', 'N/A')}`"
            }
        })
    
    # Add fix suggestion if available
    if fix and "fix" in fix and isinstance(fix["fix"], dict):
        fix_data = fix["fix"]
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*🛠️ Suggested Fix*\n```{fix_data.get('explanation', 'N/A')}```\n\n*Risk Level:* {fix_data.get('risk_level', 'N/A')}"
            }
        })
    
    # Add divider and footer
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "🤖 Generated by RootMind — Autonomous Multi-Agent AIOps Platform"
            }
        ]
    })
    
    # Send to Slack
    payload = {
        "blocks": blocks,
        "text": f"🚨 Incident detected in {service}"  # Fallback for notifications
    }
    
    try:
        response = httpx.post(
            settings.SLACK_WEBHOOK_URL,
            json=payload,
            timeout=10.0
        )
        response.raise_for_status()
        print("✅ Slack alert sent successfully!")
        return {"status": "success", "message": "Alert sent to Slack"}
    except Exception as e:
        print(f"❌ Failed to send Slack alert: {e}")
        return {"status": "failed", "error": str(e)}