"""
test_fix.py - Unit tests for fix suggestion agent

Validates patch and code suggestion formats generated by the Fix Agent.
"""

from agents.fix_agent import generate_suggested_patch


def test_generate_suggested_patch() -> None:
    """
    Test patch suggestions schema validation.
    """
    mock_rca = {
        "root_cause": "Timeout limit too low",
        "suspected_file": "app/main.py",
        "suspected_commit": "a1b2c3d4"
    }
    mock_file_content = "timeout = 5\n"
    
    result = generate_suggested_patch(mock_rca, mock_file_content)
    assert "patch_diff" in result
    assert "explanation" in result
    assert result["estimated_risk"] in ["low", "medium", "high"]
